name: Validate YAML
on:
  push:
    paths:
      - '**.yml'
      - '**.yaml'
  release:
    types: [created]

jobs:
  validate-yaml:
    name: Validate YAML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: RomanosTrechlis/actions-validate-yaml@v1.0
        with:
          schema: spec.json
          data: |-
            file1.yml
            file2.yml